# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'ipaddr'
require 'yaml'

x = YAML.load_file('config.yaml')
puts "Config: #{x.inspect}\n\n"

$private_nic_type = x.fetch('net').fetch('private_nic_type')

Vagrant.configure(2) do |config|

    config.vm.define "server-01" do |server|
      c = x.fetch('server')
      server.vm.box= "ubuntu/xenial64"
      # server.vm.guest = :linux
      server.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.cpus = c.fetch('cpus')
        v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0') and x.fetch('linked_clones')
        v.memory = c.fetch('memory')
        v.name = "server-01"
      end
      server.vm.network x.fetch('net').fetch('network_type'), ip: x.fetch('ip').fetch('server') , nic_type: $private_nic_type
      server.vm.hostname = "server-01"
      server.vm.provision "shell", path: "scripts/configure_rancher.sh",
        env: {
          'admin_password' => x.fetch('default_password'),
          'docker_version' => x.fetch('docker_version').fetch('server'),
          'rancher_version' => x.fetch('rancher_version'),
          'cluster_name' => x.fetch('cluster_name'),
          'rodeo' => x.fetch('rodeo'),
          'rancher_role' => 'server',
          'rancher_server_ip' => x.fetch('ip').fetch('server')
        }
  end

  node_ip_start = IPAddr.new(x.fetch('ip').fetch('node'))

  (1..x.fetch('node').fetch('count')).each do |i|
    c = x.fetch('node')
    hostname = "node-%02d" % i
    node_ip = IPAddr.new(node_ip_start.to_i + i - 1, Socket::AF_INET).to_s
    config.vm.define hostname do |node|
      node.vm.box   = "ubuntu/xenial64"
      # node.vm.guest = :linux
      node.vm.provider "virtualbox" do |v|
        v.cpus = c.fetch('cpus')
        v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0') and x.fetch('linked_clones')
        v.memory = c.fetch('memory')
        v.name = hostname
      end
      node.vm.network x.fetch('net').fetch('network_type'), ip: node_ip, nic_type: $private_nic_type
      node.vm.hostname = hostname
      node.vm.provision "shell", path: "scripts/configure_rancher.sh",
        env: {
          'admin_password' => x.fetch('default_password'),
          'docker_version' => x.fetch('docker_version').fetch('node'),
          'cluster_name' => x.fetch('cluster_name'),
          'rodeo' => x.fetch('rodeo'),
          'rancher_role' => x.fetch('roles').fetch(hostname, 'all'),
          'rancher_server_ip' => x.fetch('ip').fetch('server'),
          'node_ip' => node_ip
        }
    end
  end

end